In [4]:
#widen display
from IPython.core.display import display, HTML
display(HTML("<style>.container { width:95% !important; }</style>"))

In [5]:
import pandas as pd
import numpy as np
import matplotlib as plt
import gmaps

# API Keys
from config import api_key

# Configure gmaps
gmaps.configure(api_key=api_key)

In [6]:
# Read in the Dallas County Appraisal District (DCAD) property values file
zip_group_file = "Resources/zip_group_csv.csv"

#create DataFrame
summary_by_zip_df = pd.read_csv(zip_group_file)

In [9]:
#Get 5 Zipcodes with highest values
zip_group_top_and_bottom = summary_by_zip_df.head(5)

#Get 5 Zipcodes with lowest values
zip_group_top_and_bottom = zip_group_top_and_bottom.append(summary_by_zip_df.tail(5))
zip_group_top_and_bottom

,Unnamed: 0,Zipcode,PropertyValueCount,MeanPropertyValue,MeanPropertyDollarValue,Lat,Lng,City,State,bank_count,bank_rating,supermarket_count,supermarket_rating,hospital_count,hospital_rating
0,0,75205,6415,1.606362e+06,"$1,606,362",32.832584,-96.797592,Dallas,TX,46,3.627660,20,4.311111,19,3.967742
1,1,75225,7633,1.207824e+06,"$1,207,824",32.869505,-96.789557,Dallas,TX,51,3.582927,10,4.300000,6,3.664516
2,2,75201,1326,9.667580e+05,"$966,758",32.786330,-96.796253,Dallas,TX,41,3.528571,21,4.110526,17,3.945714
3,3,75209,5424,7.230552e+05,"$723,055",32.853872,-96.819022,Dallas,TX,47,3.625000,15,4.128571,15,4.088462
4,4,75230,9337,7.046378e+05,"$704,638",32.900512,-96.786879,Dallas,TX,50,3.390476,9,4.111111,15,3.492500
76,83,75203,2802,7.551809e+04,"$75,518",32.743300,-96.786879,Dallas,TX,22,3.312500,17,3.858824,4,4.471429
77,84,75172,881,6.372479e+04,"$63,725",32.602835,-96.679851,Wilmer,TX,1,0.000000,1,4.400000,0,0.000000
78,85,75216,14850,5.710002e+04,"$57,100",32.703088,-96.802949,Dallas,TX,13,2.906667,16,3.712500,6,2.733333
79,86,75215,4430,5.304015e+04,"$53,040",32.755695,-96.765460,Dallas,TX,23,3.604545,11,3.790909,14,3.882609
80,90,75210,1681,3.301014e+04,"$33,010",32.765421,-96.741371,Dallas,TX,8,2.983333,11,3.830000,12,3.794737

In [7]:
summary_by_zip_df['bank_count'].corr(summary_by_zip_df['MeanPropertyValue'])

0.5716667803740361

In [8]:
summary_by_zip_df['bank_count'].corr(summary_by_zip_df['PropertyValueCount'])

-0.03766522669374132

In [ ]:
# Store latitude and longitude in locations
top_zip_locations_to_map = list(zip(zip_group_top_and_bottom.head()['Lat'], zip_group_top_and_bottom.head()['Lng']))
bottom_zip_locations_to_map = list(zip(zip_group_top_and_bottom.tail()['Lat'], zip_group_top_and_bottom.tail()['Lng']))

In [ ]:
# Customize the size of the figure
figure_layout = {
    'width': '600px',
    'height': '600px',
    'border': '1px solid black',
    'padding': '1px',
    'margin': '0 auto 0 auto'
}

fig = gmaps.figure(layout=figure_layout)

In [ ]:
top_zips = [zipcode for zipcode in zip_group_top_and_bottom.head()['Zipcode']]
print(top_zips)

In [ ]:
# Assign the symbols layer to a variable
symbols_top = gmaps.symbol_layer(
        top_zip_locations_to_map, fill_color='navy', stroke_color='navy', hover_text='Top', scale=5)
symbols_bottom = gmaps.symbol_layer(
        bottom_zip_locations_to_map, fill_color='#f5bc42', stroke_color='#f5bc42', scale = 5)

# Add the layer to the map
fig.add_layer(symbols_top)
fig.add_layer(symbols_bottom)
fig